// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByzeMORJ6lyg7NlrQt0RjjD6snPcJVLzM',
    appId: '1:503005311143:web:2524c794687fc0d4deab82',
    messagingSenderId: '503005311143',
    projectId: 'authentication-49d38',
    authDomain: 'authentication-49d38.firebaseapp.com',
    storageBucket: 'authentication-49d38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK9VJwujz0hp8h9TBVCKKSYIyW1MGs7x8',
    appId: '1:503005311143:android:bed101637a96c6a4deab82',
    messagingSenderId: '503005311143',
    projectId: 'authentication-49d38',
    storageBucket: 'authentication-49d38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQp19abTigaqriwxhWdDf2bgGhXRqjyyU',
    appId: '1:503005311143:ios:f9e81c4cd16b87b7deab82',
    messagingSenderId: '503005311143',
    projectId: 'authentication-49d38',
    storageBucket: 'authentication-49d38.appspot.com',
    iosClientId: '503005311143-sqvtpp16209jc5mru9qf8f2akb774s84.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQp19abTigaqriwxhWdDf2bgGhXRqjyyU',
    appId: '1:503005311143:ios:f9e81c4cd16b87b7deab82',
    messagingSenderId: '503005311143',
    projectId: 'authentication-49d38',
    storageBucket: 'authentication-49d38.appspot.com',
    iosClientId: '503005311143-sqvtpp16209jc5mru9qf8f2akb774s84.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
